:::config { "language": "makefile" }
say_hello:
    @echo "Hello World"

generate:
    @echo "Creating empty text files..."
    touch file-{1..10}.txt

clean:
    @echo "Cleaning up..."
    rm *.txt
:::expectation
<pre><code data-theme='nord' data-lang='makefile' class='phiki language-makefile nord torchlight' style='background-color: #2e3440;color: #d8dee9;--theme-selection-background: #88c0d099'><!-- Syntax highlighted by Phiki and torchlight.dev --><div class='line'><span style="color: #4c566a; text-align: right; -webkit-user-select: none; user-select: none;" class="line-number"> 1</span><span class="token" style="color: #88C0D0;">say_hello:</span><span class="token" style="color: #ECEFF4;">:</span><span class="token">
</span></div><div class='line'><span style="color: #4c566a; text-align: right; -webkit-user-select: none; user-select: none;" class="line-number"> 2</span><span class="token" style="color: #d8dee9ff;">    @echo &quot;Hello World&quot;
</span></div><div class='line'><span style="color: #4c566a; text-align: right; -webkit-user-select: none; user-select: none;" class="line-number"> 3</span><span class="token">
</span></div><div class='line'><span style="color: #4c566a; text-align: right; -webkit-user-select: none; user-select: none;" class="line-number"> 4</span><span class="token" style="color: #88C0D0;">generate:</span><span class="token" style="color: #ECEFF4;">:</span><span class="token">
</span></div><div class='line'><span style="color: #4c566a; text-align: right; -webkit-user-select: none; user-select: none;" class="line-number"> 5</span><span class="token" style="color: #d8dee9ff;">    @echo &quot;Creating empty text files...&quot;
</span></div><div class='line'><span style="color: #4c566a; text-align: right; -webkit-user-select: none; user-select: none;" class="line-number"> 6</span><span class="token" style="color: #d8dee9ff;">    touch file-{1..10}.txt
</span></div><div class='line'><span style="color: #4c566a; text-align: right; -webkit-user-select: none; user-select: none;" class="line-number"> 7</span><span class="token">
</span></div><div class='line'><span style="color: #4c566a; text-align: right; -webkit-user-select: none; user-select: none;" class="line-number"> 8</span><span class="token" style="color: #88C0D0;">clean:</span><span class="token" style="color: #ECEFF4;">:</span><span class="token">
</span></div><div class='line'><span style="color: #4c566a; text-align: right; -webkit-user-select: none; user-select: none;" class="line-number"> 9</span><span class="token" style="color: #d8dee9ff;">    @echo &quot;Cleaning up...&quot;
</span></div><div class='line'><span style="color: #4c566a; text-align: right; -webkit-user-select: none; user-select: none;" class="line-number">10</span><span class="token" style="color: #d8dee9ff;">    rm *.txt
</span></div></code></pre>
:::end
<pre><code data-theme='nord' data-lang='makefile' class='phiki language-makefile nord torchlight' style='background-color: #2e3440;color: #d8dee9;--theme-selection-background: #88c0d099'><!-- Syntax highlighted by Phiki and torchlight.dev --><div class='line'><span style="color: #4c566a; text-align: right; -webkit-user-select: none; user-select: none;" class="line-number"> 1</span><span class="token" style="color: #88C0D0;">say_hello:</span><span class="token" style="color: #ECEFF4;">:</span><span class="token">
</span></div><div class='line'><span style="color: #4c566a; text-align: right; -webkit-user-select: none; user-select: none;" class="line-number"> 2</span><span class="token" style="color: #d8dee9ff;">    @echo &quot;Hello World&quot;
</span></div><div class='line'><span style="color: #4c566a; text-align: right; -webkit-user-select: none; user-select: none;" class="line-number"> 3</span><span class="token">
</span></div><div class='line'><span style="color: #4c566a; text-align: right; -webkit-user-select: none; user-select: none;" class="line-number"> 4</span><span class="token" style="color: #88C0D0;">generate:</span><span class="token" style="color: #ECEFF4;">:</span><span class="token">
</span></div><div class='line'><span style="color: #4c566a; text-align: right; -webkit-user-select: none; user-select: none;" class="line-number"> 5</span><span class="token" style="color: #d8dee9ff;">    @echo &quot;Creating empty text files...&quot;
</span></div><div class='line'><span style="color: #4c566a; text-align: right; -webkit-user-select: none; user-select: none;" class="line-number"> 6</span><span class="token" style="color: #d8dee9ff;">    touch file-{1..10}.txt
</span></div><div class='line'><span style="color: #4c566a; text-align: right; -webkit-user-select: none; user-select: none;" class="line-number"> 7</span><span class="token">
</span></div><div class='line'><span style="color: #4c566a; text-align: right; -webkit-user-select: none; user-select: none;" class="line-number"> 8</span><span class="token" style="color: #88C0D0;">clean:</span><span class="token" style="color: #ECEFF4;">:</span><span class="token">
</span></div><div class='line'><span style="color: #4c566a; text-align: right; -webkit-user-select: none; user-select: none;" class="line-number"> 9</span><span class="token" style="color: #d8dee9ff;">    @echo &quot;Cleaning up...&quot;
</span></div><div class='line'><span style="color: #4c566a; text-align: right; -webkit-user-select: none; user-select: none;" class="line-number">10</span><span class="token" style="color: #d8dee9ff;">    rm *.txt
</span></div></code></pre>